sonar.projectKey=Santiagomartins23_StartInvest
sonar.organization=santiagomartins23

sonar.projectName=StartInvest
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.dart.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/injection.config.dart,**/generated/**
